In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read the data and display the head(i.e the top records)
df = pd.read_csv("C:\\Users\\kotip\\Desktop\\Spotify_Hit _Prediction\\data\\spotify.csv")
df.head()

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
0,Lucky Man,Montgomery Gentry,spotify:track:4GiXBCUF7H6YfNQsnBRIzl,0.578,0.471,4,-7.270,1,0.0289,0.368000,0.00000,0.159,0.532,133.061,196707,4,30.88059,13,1
1,On The Hotline,Pretty Ricky,spotify:track:1zyqZONW985Cs4osz9wlsu,0.704,0.854,10,-5.477,0,0.1830,0.018500,0.00000,0.148,0.688,92.988,242587,4,41.51106,10,1
2,Clouds Of Dementia,Candlemass,spotify:track:6cHZf7RbxXCKwEkgAZT4mY,0.162,0.836,9,-3.009,1,0.0473,0.000111,0.00457,0.174,0.300,86.964,338893,4,65.32887,13,0
3,"Heavy Metal, Raise Hell!",Zwartketterij,spotify:track:2IjBPp2vMeX7LggzRN3iSX,0.188,0.994,4,-3.745,1,0.1660,0.000007,0.07840,0.192,0.333,148.440,255667,4,58.59528,9,0
4,I Got A Feelin',Billy Currington,spotify:track:1tF370eYXUcWwkIvaq3IGz,0.630,0.764,2,-4.353,1,0.0275,0.363000,0.00000,0.125,0.631,112.098,193760,4,22.62384,10,1

In [3]:
df.tail()

,track,artist,uri,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
5867,Summer Rain,Carl Thomas,spotify:track:0NBHHa8wwwmBnn3aAzX5wJ,0.667,0.6270,6,-10.488,0,0.0654,0.0972,0.000052,0.1110,0.784,186.081,232560,4,40.87045,10,1
5868,And I,Ciara,spotify:track:1Jp9n1uHB72CfK31j4mEPh,0.691,0.3890,6,-10.125,1,0.0653,0.2550,0.000000,0.0981,0.437,122.219,233840,4,81.77735,7,1
5869,"Mass in B minor BWV 232, Missa: Duetto - Chris...",Johann Sebastian Bach,spotify:track:4NIOi1ImMfdufRTsgoKjbD,0.297,0.0773,2,-23.839,1,0.0620,0.9510,0.000217,0.1210,0.401,75.916,275560,4,37.51903,11,0
5870,Loog,The Clean,spotify:track:2Qyj2nUdm8y37TCCzDasFn,0.390,0.6010,7,-8.236,0,0.0291,0.0313,0.947000,0.1190,0.439,116.122,223627,4,39.84092,11,0
5871,What The World Needs,Wynonna,spotify:track:38Q6YF0TO7E4Dq6K0zdVUk,0.539,0.7400,0,-5.566,0,0.0490,0.1940,0.000000,0.0760,0.675,170.054,217160,4,24.95471,13,1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5872 entries, 0 to 5871
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track             5872 non-null   str
 1   artist            5872 non-null   str
 2   uri               5872 non-null   str
 3   danceability      5872 non-null   float64
 4   energy            5872 non-null   float64
 5   key               5872 non-null   int64
 6   loudness          5872 non-null   float64
 7   mode              5872 non-null   int64
 8   speechiness       5872 non-null   float64
 9   acousticness      5872 non-null   float64
 10  instrumentalness  5872 non-null   float64
 11  liveness          5872 non-null   float64
 12  valence           5872 non-null   float64
 13  tempo             5872 non-null   float64
 14  duration_ms       5872 non-null   int64
 15  time_signature    5872 non-null   int64
 16  chorus_hit        5872 non-null   float64
 17  sections          5872 non-null   int64
 18  target            5872 non-null   int64
dtypes: float64(10), int64(6), str(3)
memory usage: 1.2 MB

In [5]:
print("Missing values:\n",df.isnull().sum())
print("\nDuplicate values: ",df.duplicated().sum())

Missing values:
 track               0
artist              0
uri                 0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
chorus_hit          0
sections            0
target              0
dtype: int64

Duplicate values:  0

In [6]:
print("shape: ",df.shape)

shape:  (5872, 19)

In [7]:
print("Statistical summary:\n",df.describe())

Statistical summary:
        danceability       energy          key     loudness         mode  \
count   5872.000000  5872.000000  5872.000000  5872.000000  5872.000000
mean       0.542931     0.694511     5.276396    -7.449258     0.645095
std        0.190003     0.237792     3.564153     5.102543     0.478525
min        0.058800     0.000348     0.000000   -47.327000     0.000000
25%        0.416000     0.567000     2.000000    -8.315000     0.000000
50%        0.556000     0.744000     5.000000    -6.041500     1.000000
75%        0.681000     0.885000     8.000000    -4.562500     1.000000
max        0.986000     0.999000    11.000000     1.137000     1.000000

       speechiness  acousticness  instrumentalness     liveness      valence  \
count  5872.000000   5872.000000       5872.000000  5872.000000  5872.000000
mean      0.092360      0.214374          0.150917     0.196141     0.482262
std       0.094997      0.296511          0.301452     0.161965     0.254567
min       0.022400      0.000000          0.000000     0.019300     0.000000
25%       0.036175      0.004553          0.000000     0.093700     0.278000
50%       0.052700      0.060300          0.000022     0.131000     0.486000
75%       0.107000      0.312000          0.047275     0.263000     0.687000
max       0.950000      0.996000          0.998000     0.987000     0.982000

             tempo   duration_ms  time_signature   chorus_hit     sections  \
count  5872.000000  5.872000e+03     5872.000000  5872.000000  5872.000000
mean    121.613018  2.581706e+05        3.913999    40.734295    11.056880
std      30.179885  1.395341e+05        0.404280    20.245637     5.758186
min      46.755000  1.592000e+04        0.000000     0.000000     1.000000
25%      96.984000  2.068130e+05        4.000000    27.507507     9.000000
50%     119.999000  2.380065e+05        4.000000    36.037160    10.000000
75%     141.495250  2.791600e+05        4.000000    47.889570    12.000000
max     213.233000  4.170227e+06        5.000000   262.615400   169.000000

            target
count  5872.000000
mean      0.500000
std       0.500043
min       0.000000
25%       0.000000
50%       0.500000
75%       1.000000
max       1.000000

In [8]:
print("Target distribution: ")
print(df['target'].value_counts())
print(f"\nHit %:{df['target'].mean()*100:.2f}%")

Target distribution:
target
1    2936
0    2936
Name: count, dtype: int64

Hit %:50.00%